export const SUBLIBTN='SUBLIBTN'
export const DEINCREMENT='DEINCREMENT'
export const CLICKODD='CLICKODD'
export const CLICKASYNC='CLICKASYNC'
export const GETSECONDMENU='GETSECONDMENU'
export const LST='LST'
export const GETTABLEDATA='GETTABLEDATA'
export const GETGJJS='GETGJJS'
export const ISOPEN='ISOPEN'
export const CLOSEDIOAG='CLOSEDIOAG'



